### ISSUE TITLE
BluetoolFixup broken on macOS Sonoma and Ventura 13.4+

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#46]
Due to a regression in BluetoolFixup, Bluetooth may be broken on later versions of Ventura and macOS Sonoma.

The below NVRAM patch is required for BluetoolFixup on 13.4+

```yaml
# Ventura 13.4 fix for BluetoolFixup
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      bluetoothInternalControllerInfo: Data | 00000000 00000000 00000000 0000
      bluetoothExternalDongleFailed:   Data | 00
```
(Fix originally contributed by @qcTimb3rlandqc in [IntelBluetoothFirmware#435](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435#issuecomment-1555911943))

Alternatively, an updated binary is provided by @zxystd [here](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/437#issuecomment-1579931908), which should also be applicable for users updating to macOS Sonoma.
